### ISSUE TITLE
Posible crash al cerrar la herramienta

### ISSUE THREAD

**Issue by cybercamphackathon** [DarkAnHell/FastPhish#10]
https://github.com/DarkAnHell/FastPhish/blob/a2cf97c85e78f53b4c5d36ad1a9694d8333bf3a3/cmd/ctdemo/main.go#L36

¿Esto no se rompe al cerrar el canal? Lo mejor sería meter algo en el canal para que el <-done que tenéis más abajo saliera de forma más elegante.

**Comment by jimen0** [comment]
This isn't a valid crash.
But [this](https://github.com/DarkAnHell/FastPhish/blob/master/pkg/analyzer/levenshtein/levenshtein.go) could crash indeed.
